sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDEQiEEUHmrEunzy9tq
    access-key-secret: meQpxNr7tQ8gbz8fIUWqFBdVYy1vBQ
    bucket-name: sky-takeout5
  redis:
    host: localhost
    port: 6379
    password: 931886861
    database: 0
  wechat:
    appid: wxed05a1343cb324cd
    secret: 1d8406a7f8965673c245767b20de1a47

